version: '2.2'
services:
  app:
    container_name: contenedor_python
    image: prueba:1
    restart: always
    environment:
      NAME: ${NAME}
      USER: ${USER}
      PASSWORD: ${PASS}
      HOST: basededatos
      DJ_USER: ${DJ_USER}
      DJ_PASSWORD: ${DJ_PASSWORD}
      DJ_EMAIL: ${DJ_EMAIL}
      URL: ${URL}
    ports:
      - ${PORT}:3000
    depends_on:
      - db
  db:
    container_name: basededatos
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${NAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASS}
      MYSQL_ROOT_PASSWORD: ${ROOT}
    volumes:
      - mariadb_data1:/var/lib/mysql
volumes:
    mariadb_data1:
